### ISSUE TITLE
gem install synapse error

### ISSUE THREAD

**Issue by zouyx** [airbnb/synapse#155]
hi 
i have run the command as below
gem install synapse --install-dir /opt/smartstack/synapse --no-ri --no-rdoc

but get the error,i don't know what it is mean, can you help me to fix it ?

error message as below:
```
/opt/smartstack/synapse/gems/mini_portile2-2.0.0/lib/mini_portile2/mini_portile.rb:79:in `apply_patch': Failed to complete patch task; patch(1) or git(1) is required. (RuntimeError)
	from /opt/smartstack/synapse/gems/mini_portile2-2.0.0/lib/mini_portile2/mini_portile.rb:87:in `block in patch'
	from /opt/smartstack/synapse/gems/mini_portile2-2.0.0/lib/mini_portile2/mini_portile.rb:85:in `each'
	from /opt/smartstack/synapse/gems/mini_portile2-2.0.0/lib/mini_portile2/mini_portile.rb:85:in `patch'
	from /opt/smartstack/synapse/gems/mini_portile2-2.0.0/lib/mini_portile2/mini_portile.rb:148:in `cook'
	from extconf.rb:289:in `block (2 levels) in process_recipe'
	from extconf.rb:182:in `block in chdir_for_build'
	from extconf.rb:181:in `chdir'
	from extconf.rb:181:in `chdir_for_build'
	from extconf.rb:288:in `block in process_recipe'
	from extconf.rb:187:in `tap'
	from extconf.rb:187:in `process_recipe'
	from extconf.rb:490:in `<main>'
ERROR:  Error installing synapse:
	ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
extconf failed, exit code 1

Gem files will remain installed in /opt/smartstack/synapse/gems/nokogiri-1.6.8.rc1 for inspection.
Results logged to /opt/smartstack/synapse/extensions/x86_64-linux/2.1.0-static/nokogiri-1.6.8.rc1/gem_make.out
```

**Comment by jolynch** [comment]
@zouyx Thanks for the report. What system / environment are you trying to install on?

`` Failed to complete patch task; patch(1) or git(1) is required. (RuntimeError)`` makes me think that you need git or patch on your system. Can you try installing one of those and let me know how it goes?

**Comment by rickypai** [comment]
this can be fixed with installing the required package `patch` with `apt-get install patch`
