### ISSUE TITLE
undefined method `fetch' for nil:NilClass

### ISSUE THREAD

**Issue by Jaykah** [airbnb/synapse#176]
I started getting the following error on a few machines where the latest Synapse release was deployed. Still checking whether anything else could have caused it, but any tips would be appreciated:

```
I, [2016-02-23T19:44:59.815064 #1821]  INFO -- Synapse::Synapse: synapse: starting...
I, [2016-02-23T19:44:59.815198 #1821]  INFO -- Synapse::ServiceWatcher::BaseWatcher: synapse: starting stub watcher; this means doing nothing at all!
I, [2016-02-23T19:44:59.815262 #1821]  INFO -- Synapse::Synapse: synapse: configuring haproxy
W, [2016-02-23T19:44:59.815437 #1821]  WARN -- Synapse::Haproxy: synapse: unhandled error reading stats socket: #<Errno::ECONNREFUSED: Connection refused - connect(2) for /var/haproxy/stats.sock>
E, [2016-02-23T19:44:59.815793 #1821] ERROR -- Synapse::Synapse: synapse: encountered unexpected exception #<NoMethodError: undefined method `fetch' for nil:NilClass> in main thread
W, [2016-02-23T19:44:59.815891 #1821]  WARN -- Synapse::Synapse: synapse: exiting; sending stop signal to all watchers
I, [2016-02-23T19:44:59.815950 #1821]  INFO -- Synapse::ServiceWatcher::BaseWatcher: synapse: stopping watcher proddb using default stop handler
/usr/local/lib/ruby/gems/2.2.0/gems/synapse-0.13.1/lib/synapse/haproxy.rb:702:in `generate_backend_stanza': undefined method `fetch' for nil:NilClass (NoMethodError)
        from /usr/local/lib/ruby/gems/2.2.0/gems/synapse-0.13.1/lib/synapse/haproxy.rb:602:in `block in generate_config'
        from /usr/local/lib/ruby/gems/2.2.0/gems/synapse-0.13.1/lib/synapse/haproxy.rb:599:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/synapse-0.13.1/lib/synapse/haproxy.rb:599:in `generate_config'
        from /usr/local/lib/ruby/gems/2.2.0/gems/synapse-0.13.1/lib/synapse/haproxy.rb:585:in `update_config'
        from /usr/local/lib/ruby/gems/2.2.0/gems/synapse-0.13.1/lib/synapse.rb:61:in `block (2 levels) in run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/synapse-0.13.1/lib/synapse.rb:59:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/synapse-0.13.1/lib/synapse.rb:59:in `block in run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/synapse-0.13.1/lib/synapse.rb:52:in `loop'
        from /usr/local/lib/ruby/gems/2.2.0/gems/synapse-0.13.1/lib/synapse.rb:52:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/synapse-0.13.1/bin/synapse:60:in `<top (required)>'
        from /usr/local/bin/synapse:23:in `load'
        from /usr/local/bin/synapse:23:in `<main>'
```

**Comment by jolynch** [comment]
@Jaykah are you using the state file (``state_file_path``)?

I wonder if we need to set @seen back to ``{}`` in the [rescue](https://github.com/airbnb/synapse/blob/abbdf2a34cce4ba7e0f164ed39ef010d632f9241/lib/synapse/haproxy.rb#L559)

**Comment by Jaykah** [comment]
Yes, I am
```
  state_file_path: /tmp/synapse/state.json
```

However it is currently empty since Synapse could not start and that's a fresh build.

**Comment by jolynch** [comment]
@Jaykah does the file exist but is empty?

**Comment by Jaykah** [comment]
Correct

**Comment by jolynch** [comment]
@Jaykah This is a regression in how ``JSON`` handles an empty file. It used to properly raise an exception and now it returns nil. Bugfix otw.

```
~/Hacking » rbenv shell 2.1.2; rbenv rehash                                                                                                             
~/Hacking » ruby -e "require 'json'; puts JSON.method(:load).source_location; foo = JSON.load(File.read('/tmp/synapse/state.json')); puts foo.nil?"
/.../.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/json-1.8.2/lib/json/common.rb
322
true

~/Hacking » rbenv shell 1.9.3-p448; rbenv rehash                                                                                                        

~/Hacking » ruby -e "require 'json'; puts JSON.method(:load).source_location; foo = JSON.load(File.read('/tmp/synapse/state.json')); puts foo.nil?"      
/.../.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/json/common.rb
295
/.../.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/json/common.rb:148:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
	from /.../.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/json/common.rb:148:in `new'
	from /.../.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/json/common.rb:148:in `parse'
	from /.../.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/json/common.rb:309:in `load'
	from -e:1:in `<main>'
```

**Comment by jolynch** [comment]
@Jaykah we'll be doing a gem release in a little bit to pick up a few other changes. As a short term fix just remove the file and as a long term fix this will get rolled into the next release.

**Comment by Jaykah** [comment]
Thanks @jolynch !
