### ISSUE TITLE
service_conf_dir no longer a valid top level config key

### ISSUE THREAD

**Issue by GnawNom** [airbnb/synapse#226]
Tried upgrading from 0.12.2 to 0.14.1, ran into this error:
```
/opt/rh/rh-ruby22/root/usr/local/share/gems/gems/synapse-0.14.1/lib/synapse/config_generator.rb:15:in `rescue in create': Specified a config generator of service_conf_dir, which could not be found: cannot load such file -- synapse/config_generator/service_conf_dir (ArgumentError)
        from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/synapse-0.14.1/lib/synapse/config_generator.rb:8:in `create'
        from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/synapse-0.14.1/lib/synapse.rb:99:in `block in create_config_generators'
        from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/synapse-0.14.1/lib/synapse.rb:96:in `each'
        from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/synapse-0.14.1/lib/synapse.rb:96:in `create_config_generators'
        from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/synapse-0.14.1/lib/synapse.rb:17:in `initialize'
        from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/synapse-0.14.1/bin/synapse:59:in `new'
        from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/synapse-0.14.1/bin/synapse:59:in `<top (required)>'
        from /opt/rh/rh-ruby22/root/usr/local/bin/synapse:23:in `load'
        from /opt/rh/rh-ruby22/root/usr/local/bin/synapse:23:in `<main>'
```
This is the synapse conf we were using:
```
{
  "service_conf_dir": "/box/etc/smartstack/synapse_services",
  "haproxy": {
    "bind_address": "0.0.0.0",
    "reload_command": "sudo /sbin/service haproxy reload",
    "config_file_path": "/etc/haproxy/haproxy.cfg",
    "state_file_path": "/box/etc/smartstack/synapse_state.json",
    "state_file_ttl": "86400",
    "socket_file_path": "/var/lib/haproxy/stats",
    "global": [
      "daemon",
      "user haproxy",
      "group haproxy",
      "maxconn 20000",
      "log     127.0.0.1 local1",
      "stats   socket /var/lib/haproxy/stats mode 666 level admin",
      "pidfile /var/run/haproxy.pid"
    ],
    "defaults": [
      "log      global",
      "option   dontlognull",
      "option   contstats",
      "option   tcplog",
      "option   abortonclose",
      "maxconn  20000",
      "retries  3",
      "timeout  connect 500",
      "timeout  client  2m",
      "timeout  server  1m",
      "balance  roundrobin"
    ],
    "extra_sections": {
      "listen stats": [
        "bind :8081",
        "mode http",
        "stats enable",
        "stats uri /",
        "stats refresh 15s"
      ]
    }
  }
}
```
Is the service_conf_dir directive no longer supported in 0.14.1?

**Comment by jolynch** [comment]
Nope, this is a bug, thanks for the PR will merge shortly.

**Comment by jolynch** [comment]
@GnawNom Can you try out 0.14.3 and let me know if that works? 0.14 had a large refactor to support alternative configuration generators (e.g. nginx + haproxy + w.e. hot new proxy comes out) and we're still dogfooding at Yelp.
